export enum FilterQueriesKeys {
  SECURITY_USERS_ID = 'security_user_id',
  SECURITY_USERS_SEX = 'security_user_sex',
  SECURITY_USERS_PROFILE = 'security_user_profile',
  SECURITY_USERS_NAME = 'security_user_name',
  SECURITY_USERS_LASTNAME = 'security_user_lastname',
  SECURITY_ROLES_ID = 'security_role_id',
  SECURITY_ROLES_NAME = 'security_role_name',
  SECURITY_ROLES_ACTIVE = 'security_role_active',
  SECURITY_ROLES_USERS_COUNT = 'security_role_users_count',
  SECURITY_COMPANIES_ID = 'security_company_id',
  SECURITY_COMPANIES_NAME = 'security_company_name',
  SECURITY_COMPANIES_NAME_SHORT = 'security_company_name_short',
  SECURITY_COMPANIES_ACTIVE = 'security_company_active',
  SECURITY_COMPANIES_USERS_COUNT = 'security_company_users_count',
  ENS_TEAM_ID = 'ens_team_id',
  ENS_TEAM_NAME = 'ens_team_name',
  ENS_TEAM_ACTIVE = 'ens_team_is_active',
  ENS_TEAM_NIVEL_0 = 'ens_team_nivel_0',
  ENS_TEAM_NIVEL_1 = 'ens_team_nivel_1',
  ENS_TEAM_NIVEL_2 = 'ens_team_nivel_2',
  ENS_SERVICIOS_ID = 'ens_servicios_id',
  ENS_SERVICIOS_NAME = 'ens_servicios_name',
  ENS_SERVICIOS_ACTIVE = 'ens_servicios_is_active',
  ENS_LIBROS_ID = 'ens_libros_id',
  ENS_LIBROS_NAME = 'ens_libros_name',
  ENS_LIBROS_ACTIVE = 'ens_libros_is_active',
}